$ErrorActionPreference = "Stop"
$ROOT = "C:\Users\Clamps\.openclaw\workspace"
Set-Location $ROOT

New-Item -ItemType Directory -Force -Path "$ROOT\docs\claude-reports" | Out-Null
New-Item -ItemType Directory -Force -Path "$ROOT\data\logs\claude-tasks" | Out-Null
New-Item -ItemType Directory -Force -Path "$ROOT\data\state\locks" | Out-Null

$timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm"
$logFile = "$ROOT\data\logs\claude-tasks\researcher_$timestamp.log"
$sharedLockDir = "$ROOT\data\state\locks\quandalf_pipeline.lockdir"

if (Test-Path -LiteralPath $sharedLockDir) {
  try { python scripts/log_event.py --agent "claude-advisor" --action "strategy_research" --status WARN --summary "Skipped: shared Quandalf pipeline lock is held by another task." | Out-Null } catch {}
  Write-Output "[$timestamp] Skipped: shared Quandalf pipeline lock held" | Tee-Object -FilePath $logFile -Append
  exit 0
}

New-Item -ItemType Directory -Path $sharedLockDir | Out-Null

try {

function Test-IsModelRateLimited([string]$text) {
  if ([string]::IsNullOrWhiteSpace($text)) { return $false }
  return ($text -match '(?i)rate\s*limit|too\s*many\s*requests|\b429\b|quota|overloaded|temporar(?:y|ily)\s+unavailable|cyber_policy_violation')
}

function Emit-RateLimitEvent([string]$status, [string]$summary) {
  try {
    python scripts/log_event.py --agent "claude-advisor" --action "model_rate_limit" --status $status --summary $summary | Out-Null
  } catch {}
}

function Invoke-ClaudeWithRetry([string]$promptText, [string]$logPath, [int]$maxAttempts = 2) {
  for ($attempt = 1; $attempt -le $maxAttempts; $attempt++) {
    $out = & claude -p $promptText --allowedTools "Read,Write,Bash(python scripts/log_event.py*),Bash(python scripts/quandalf/build_index.py*)" 2>&1 | Tee-Object -FilePath $logPath -Append | Out-String
    $exitCode = $LASTEXITCODE
    $isRateLimited = Test-IsModelRateLimited -text $out

    if ($exitCode -eq 0) {
      return 0
    }

    if ($isRateLimited -and $attempt -lt $maxAttempts) {
      Emit-RateLimitEvent -status "WARN" -summary "Researcher rate-limited on attempt $attempt; backing off 90s and retrying."
      Start-Sleep -Seconds 90
      continue
    }

    if ($isRateLimited) {
      Emit-RateLimitEvent -status "FAIL" -summary "Researcher blocked by model rate-limit/policy after retry."
    }

    return $exitCode
  }

  return 1
}

$prompt = @"
MODE: STRATEGY_RESEARCHER

You are the Senior Quant Researcher for AutoQuant.
Your goal is NOT only strategy ideas. Build and maintain Quandalf's evolving brain.

READ these files:
1. All outcome notes in artifacts/outcomes/ (latest 30 files across all date folders)
2. The doctrine file: docs/DOCTRINE/analyser-doctrine.md
3. The latest 10 backtest results in artifacts/backtests/
4. Current signal templates: scripts/backtester/signal_templates.py
5. Previous advisory (if exists): docs/claude-reports/STRATEGY_ADVISORY.md
6. Recent research cards from video ingestion in artifacts/research_cards/ (latest 10 files if they exist)
7. Any strategy specs generated by Claude in artifacts/claude-specs/
8. QUANDALF_BRAIN contract: docs/CONTRACTS/QUANDALF_BRAIN.md
9. Current brain objects in brain/{facts,rules,constraints,failures}
10. Current brain journal entries in brain/journal/
11. Runtime context: docs/shared/QUANDALF_RUNTIME_CONTEXT.md

ANALYSE for:
- Durable market/regime knowledge (not just one-off ideas)
- What has become stronger evidence vs weaker evidence
- Which patterns should be encoded as long-term rules
- What video research changed your mental model this cycle
- Which assumptions should be challenged next
- Whether recent tests support or invalidate prior beliefs

WRITE these outputs:

A) Advisory report to:
docs/claude-reports/STRATEGY_ADVISORY.md

Sections:
- Executive Summary
- Failing Patterns
- Promising Directions
- Template Health
- Regime Insights
- Recommended Directives
- Doctrine Gaps
- Suggestions For Asz

B) Update QUANDALF_BRAIN object memory under:
brain/{facts,rules,constraints,failures}

Rules for BRAIN updates:
- Must follow docs/CONTRACTS/QUANDALF_BRAIN.md
- Keep it structured and cumulative (no fluff)
- Update with concrete evidence and confidence
- Prefer evidence bullets with metrics when available

C) Append exactly one concise pointer-first brain journal entry to:
brain/journal/

Journal entry minimum:
- id
- ts
- pointers (object ids and/or evidence paths)

D) Append/update one human-readable operator journal entry to:
docs/shared/QUANDALF_JOURNAL.md

Operator journal format (MANDATORY, match historical Entry 007 style):
- Results
- Key Insights
- What I’m Testing Next
- Suggestions for Asz (if any)

Style constraints (MANDATORY):
- Max 4 sections only (exactly the headings above)
- 2-6 bullets per section
- Max 900 words total
- No large tables, no long narrative blocks
- Keep concise but substantial (not one-line stubs)

IMPORTANT:
- Do NOT include machine-directive JSON in operator journal content.
- Keep it readable and concise.

After writing, run:
python scripts/quandalf/build_index.py

After writing and index build, emit notification:
python scripts/log_event.py --agent "claude-advisor" --action "strategy_research" --status OK --summary "Advisory+brain+journal updated and indexed: [1-line key finding]"
"@

Write-Output "[$timestamp] Starting Strategy Researcher..." | Tee-Object -FilePath $logFile -Append
$taskExit = Invoke-ClaudeWithRetry -promptText $prompt -logPath $logFile -maxAttempts 2

$advisory = "$ROOT\docs\claude-reports\STRATEGY_ADVISORY.md"
$journal = "$ROOT\docs\shared\QUANDALF_JOURNAL.md"
if ($taskExit -eq 0) {
  $indexOut = & python scripts/quandalf/build_index.py 2>&1 | Tee-Object -FilePath $logFile -Append | Out-String
  if ($LASTEXITCODE -ne 0) {
    Write-Output "Index build failed after researcher success: $indexOut" | Tee-Object -FilePath $logFile -Append
    $taskExit = 1
  }
}

if ($taskExit -eq 0) {
  if (Test-Path $journal) {
    powershell -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File "$ROOT\scripts\claude-tasks\send-quandalf-cycle-summary.ps1" `
      -TaskLabel "journal cycle" `
      -SourceFile $journal | Out-Null
  } elseif (Test-Path $advisory) {
    powershell -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File "$ROOT\scripts\claude-tasks\send-quandalf-cycle-summary.ps1" `
      -TaskLabel "research cycle" `
      -SourceFile $advisory | Out-Null
  }
}

Write-Output "[$timestamp] Completed: $taskExit" | Tee-Object -FilePath $logFile -Append
exit $taskExit
}
finally {
  Remove-Item -LiteralPath $sharedLockDir -Recurse -Force -ErrorAction SilentlyContinue
}
