$ErrorActionPreference = "Stop"
$ROOT = "C:\Users\Clamps\.openclaw\workspace"
Set-Location $ROOT

New-Item -ItemType Directory -Force -Path "$ROOT\docs\claude-reports" | Out-Null
New-Item -ItemType Directory -Force -Path "$ROOT\data\logs\claude-tasks" | Out-Null

$timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm"
$logFile = "$ROOT\data\logs\claude-tasks\researcher_$timestamp.log"

function Test-IsModelRateLimited([string]$text) {
  if ([string]::IsNullOrWhiteSpace($text)) { return $false }
  return ($text -match '(?i)rate\s*limit|too\s*many\s*requests|\b429\b|quota|overloaded|temporar(?:y|ily)\s+unavailable|cyber_policy_violation')
}

function Emit-RateLimitEvent([string]$status, [string]$summary) {
  try {
    python scripts/log_event.py --agent "claude-advisor" --action "model_rate_limit" --status $status --summary $summary | Out-Null
  } catch {}
}

function Invoke-ClaudeWithRetry([string]$promptText, [string]$logPath, [int]$maxAttempts = 2) {
  for ($attempt = 1; $attempt -le $maxAttempts; $attempt++) {
    $out = & claude -p $promptText --allowedTools "Read,Write,Bash(python scripts/log_event.py*)" 2>&1 | Tee-Object -FilePath $logPath -Append | Out-String
    $exitCode = $LASTEXITCODE
    $isRateLimited = Test-IsModelRateLimited -text $out

    if ($exitCode -eq 0) {
      return 0
    }

    if ($isRateLimited -and $attempt -lt $maxAttempts) {
      Emit-RateLimitEvent -status "WARN" -summary "Researcher rate-limited on attempt $attempt; backing off 90s and retrying."
      Start-Sleep -Seconds 90
      continue
    }

    if ($isRateLimited) {
      Emit-RateLimitEvent -status "FAIL" -summary "Researcher blocked by model rate-limit/policy after retry."
    }

    return $exitCode
  }

  return 1
}

$prompt = @"
MODE: STRATEGY_RESEARCHER

You are the Senior Quant Researcher for AutoQuant.
Your goal is NOT only strategy ideas. Build and maintain Quandalf's evolving brain.

READ these files:
1. All outcome notes in artifacts/outcomes/ (latest 30 files across all date folders)
2. The doctrine file: docs/DOCTRINE/analyser-doctrine.md
3. The latest 10 backtest results in artifacts/backtests/
4. Current signal templates: scripts/backtester/signal_templates.py
5. Previous advisory (if exists): docs/claude-reports/STRATEGY_ADVISORY.md
6. Recent research cards from video ingestion in artifacts/research_cards/ (latest 10 files if they exist)
7. Any strategy specs generated by Claude in artifacts/claude-specs/
8. Current long-term knowledge base: docs/shared/QUANDALF_BRAIN.md (if exists)
9. Current journal: docs/shared/QUANDALF_JOURNAL.md

ANALYSE for:
- Durable market/regime knowledge (not just one-off ideas)
- What has become stronger evidence vs weaker evidence
- Which patterns should be encoded as long-term rules
- What video research changed your mental model this cycle
- Which assumptions should be challenged next
- Whether recent tests support or invalidate prior beliefs

WRITE these outputs:

A) Advisory report to:
docs/claude-reports/STRATEGY_ADVISORY.md

Sections:
- Executive Summary
- Failing Patterns
- Promising Directions
- Template Health
- Regime Insights
- Recommended Directives
- Doctrine Gaps
- Suggestions For Asz

B) Update long-term brain file:
docs/shared/QUANDALF_BRAIN.md

Rules for BRAIN update:
- Keep it structured and cumulative (no fluff)
- Update these sections with concrete evidence and confidence:
  - Validated Edges
  - Invalidated / Weak Patterns
  - Regime Intelligence
  - Execution & Risk Lessons
  - Video-Derived Insights (general concepts, not just strategies)
  - Open Questions / Next Experiments
- Prefer evidence bullets with metrics when available

C) Append exactly one new concise journal entry to:
docs/shared/QUANDALF_JOURNAL.md

Journal entry format:
- What I learned this cycle
- What changed in my thinking
- What I’m testing next
- Suggestions for Asz (if any)

After writing, emit notification:
python scripts/log_event.py --agent "claude-advisor" --action "strategy_research" --status OK --summary "Advisory+brain+journal updated: [1-line key finding]"
"@

Write-Output "[$timestamp] Starting Strategy Researcher..." | Tee-Object -FilePath $logFile -Append
$taskExit = Invoke-ClaudeWithRetry -promptText $prompt -logPath $logFile -maxAttempts 2

$journal = "$ROOT\docs\shared\QUANDALF_JOURNAL.md"
$advisory = "$ROOT\docs\claude-reports\STRATEGY_ADVISORY.md"
if ($taskExit -eq 0) {
  if (Test-Path $journal) {
    powershell -ExecutionPolicy Bypass -File "$ROOT\scripts\claude-tasks\send-quandalf-cycle-summary.ps1" `
      -TaskLabel "journal cycle" `
      -SourceFile $journal | Out-Null
  } elseif (Test-Path $advisory) {
    powershell -ExecutionPolicy Bypass -File "$ROOT\scripts\claude-tasks\send-quandalf-cycle-summary.ps1" `
      -TaskLabel "research cycle" `
      -SourceFile $advisory | Out-Null
  }
}

Write-Output "[$timestamp] Completed: $taskExit" | Tee-Object -FilePath $logFile -Append
exit $taskExit
